### ISSUE TITLE
Event subscription and notifications should be aligned with API Design Guidelines

### ISSUE THREAD

**Issue by rartych** [camaraproject/ConnectivityInsights#17]
**Problem description**
Event subscription and notifications is not aligned with API Design Guidelines

**Expected behavior**
The specification should follow recommendations of chapter [12. Subscription, Notification & Event](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#12-subscription-notification--event) in API Design Guidelines

**Alternative solution**
The Design Guidelines may need to be updated for `monitoringFrequency ` or `maximumNumberOfNotifications` subscription parameters

**Additional context**
The example of eventing is in [Geofencing API](https://github.com/camaraproject/DeviceLocation/blob/main/code/API_definitions/geofencing.yaml) of Device Location subproject

**Comment by Kevsy** [comment]
Thanks @rartych and agreed- we'll add this in the next PR (which will also incorporate further alignments with Design Guidelines)

**Comment by Kevsy** [comment]
Fixed in #22
