### ISSUE TITLE
Event Notification for subscription API

### ISSUE THREAD

**Issue by SyeddR** [camaraproject/ConnectivityInsights#29]
**Problem description**
Implement cloud event based callback notification for the subscription API

**Possible evolution**

Reference commonalities [API design guideline ](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#122-event-notification)

**Alternative solution**

**Additional context**

**Comment by Kevsy** [comment]
Hi @SyeddR , this was previously raised in #17 (now closed) and was fixed in PR #22 (now merged)
