### ISSUE TITLE
update API spec to meet latest API standards guidelines.

### ISSUE THREAD

**Issue by maheshc01** [camaraproject/ConnectivityInsights#36]
**Problem description**
There has been recent updates to the API standards as adopted by Commonalities working group which needs to be incorporated into connectivity insights API spec

**Expected action**
updates yaml to adhere to the latest standards and use the linting rules to confirm compliance.

**Additional context**

**Comment by Kevsy** [comment]
@maheshc01 do you have any pointers to the changes? I can then check if I have already rolled them in to my PR. Thanks!

**Comment by maheshc01** [comment]
I came across 1 thread in commonalities which mandates prepending "+" to phone number. I havent checked thoroughly to see if there are more updates which would impact connectivity insights API. 
Created this issue for tracking purpose.

**Comment by iamdatanick** [comment]
Ad tech follows this structure

<https://en.m.wikipedia.org/wiki/E.164>
[1200px-Phone_number_setup.png]
E.164<https://en.m.wikipedia.org/wiki/E.164>
wikipedia.org<https://en.m.wikipedia.org/wiki/E.164>


On Apr 4, 2024, at 12:12 PM, Mahesh ***@***.***> wrote:

﻿

I came across 1 thread in commonalities which mandates prepending "+" to phone number. I havent checked thoroughly to see if there are more updates which would impact connectivity insights API.
Created this issue for tracking purpose.

**Comment by Kevsy** [comment]
Device identifiers are modelled in the [CAMARA Common artifacts](https://github.com/camaraproject/Commonalities/blob/main/artifacts/CAMARA_common.yaml) - so we just need to adopt those (which includes the prepended '+' as @iamdatanick mentions above)
