### ISSUE TITLE
Provide feedback and align with upcoming explicit subscription related changes in commonalities

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/ConnectivityInsights#42]
**Problem description**
There are currently active discussions in commonalities on solving some issues regarding explicit subscriptions. This will bring some breaking changes to the APIs which offer explicit subscriptions. The proposal has been documented here https://github.com/camaraproject/Commonalities/issues/185. 

Kindly provide your feedback from the perspective of this subproject. We already have feedback from other subprojects which use explicit subscriptions (for e.g. device-status, device-location and sim-swap). It will also help this subproject to plan/prep for upcoming changes.

**Possible evolution**
Provide feedback to the proposal https://github.com/camaraproject/Commonalities/issues/185 as comments.

**Alternative solution**

**Additional context**

**Comment by bigludo7** [comment]
Hello ConnectivityInsight team,
New model for subscription is now defined and should be use in all our CAMARA subscription resource.
You have the guideline [here ](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#12-subscription-notification--event)and a subscription template [here](https://github.com/camaraproject/Commonalities/blob/main/artifacts/camara-cloudevents/event-subscription-template.yaml).
Happy to answer any question :) 
Thanks for your consideration.

cc: @shilpa-padgaonkar

**Comment by maheshc01** [comment]
fixed as part of #40
