### ISSUE TITLE
docs: correct the CHANGELOG

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/ConnectivityInsights#74]
**Problem description**

L21/22: template proposed here API-name1 vx.y.z (with version number)
L34: headline "Main changes" is not needed here, line 35 can follow directly after line 31.
L35: should be mentioned that his is the first release of the API

**Expected behavior**

Corrections as indicated above

**Alternative solution**

**Additional context**

**Comment by maheshc01** [comment]
fixed in [03ea4c3](https://github.com/camaraproject/ConnectivityInsights/pull/67/commits/03ea4c3a667f106bf98c77c97d8b1c090b6b1149)
