### ISSUE TITLE
fix: subscriptions to move to dedicated API

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/ConnectivityInsights#75]
**Problem description**

subscriptions endpoints don't follow the guidelines in https://github.com/camaraproject/Commonalities/blob/r0.4.0-rc.2/documentation/API-design-guidelines.md#resource-based-explicit-subscription
it must be a separate API with -subscriptions in the name

**Expected behavior**

Create new API,  `connectivity-insights-subscriptions`. Also note further comments from the [PR review](https://github.com/camaraproject/ConnectivityInsights/pull/67#issuecomment-2286877804)

**Alternative solution**

**Additional context**

**Comment by maheshc01** [comment]
fixed in [a23e245](https://github.com/camaraproject/ConnectivityInsights/pull/67/commits/a23e24544432de670999c33429723c2c46eea6bb) and [66d63bd](https://github.com/camaraproject/ConnectivityInsights/pull/67/commits/66d63bdd5f4dfe38517af6dc893375b864cb2eaf)

**Comment by rartych** [comment]
I have made a number of suggestions in PR #67  to align event types and scope names with Design Guidelines ch. 11 & 12.
I hope there is no mistake.
