### ISSUE TITLE
fix: scope name is wrong

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/ConnectivityInsights#77]
**Problem description**
L36 & 78 & 129 & 169
scope naming: connectivity_insights:policy:write -> application-profiles:write (resource is optional according to https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#1161-scope-naming, otherwise it would be application-profiles:application-profiles:write)

**Expected behavior**

Fix per guidelines (as described above)

**Alternative solution**

**Additional context**

**Comment by maheshc01** [comment]
fixed with commit https://github.com/camaraproject/ConnectivityInsights/commit/a02c36e36d3b1267a185eb61f0cb1a631e983266
