### ISSUE TITLE
fix: change content-type wildcard to application/json

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/ConnectivityInsights#78]
**Problem description**

L48  and L99  have `"*/*"`, but API Design Guidelines mandate `application/json` (comment applies also to connectivity-insights.yaml)
**Expected behavior**

Change wildcard to  `application/json` in L48 and L99

**Alternative solution**

**Additional context**

**Comment by maheshc01** [comment]
fixed with commit https://github.com/camaraproject/ConnectivityInsights/commit/a02c36e36d3b1267a185eb61f0cb1a631e983266
