### ISSUE TITLE
fix: return full resource representation

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/ConnectivityInsights#81]
**Problem description**

L58 - only the ApplicationProfileId is returned,  and not the full representation of the resource object? (that is inconsistent with updateApplicationProfile where the complete resource object is returned)
**Expected behavior**

Return the full resource representation

**Alternative solution**

**Additional context**

**Comment by maheshc01** [comment]
fixed with commit https://github.com/camaraproject/ConnectivityInsights/commit/a02c36e36d3b1267a185eb61f0cb1a631e983266
