### ISSUE TITLE
fix: unnecessary 404 response

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/ConnectivityInsights#82]
**Problem description**

L65 - 404 is not an expected response, as the resource will be just created

**Expected behavior**

Remove 404 from this response

**Alternative solution**

**Additional context**

**Comment by maheshc01** [comment]
fixed with commit https://github.com/camaraproject/ConnectivityInsights/commit/a02c36e36d3b1267a185eb61f0cb1a631e983266
