### ISSUE TITLE
fix: clarify need for 409 Conflict

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/ConnectivityInsights#83]
**Problem description**

L67 & L159 & L195 
It is not clear which kind of "409 CONFLICT" could be expected here and which test case would generate this error message

**Expected behavior**

Either remove 409 Conflict, or explain the Test Case which could result in it.

**Alternative solution**

**Additional context**

**Comment by maheshc01** [comment]
fixed with commit https://github.com/camaraproject/ConnectivityInsights/commit/a02c36e36d3b1267a185eb61f0cb1a631e983266
