### ISSUE TITLE
fix: consider PUT vs PATCH

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/ConnectivityInsights#84]
**Problem description**

L75: "PUT" will replace the complete resource object. It would also require some more definition what happens if
a) the applicationProfileId in the path does not yet exist (PUT would allow to create it, but I don't think that's what you want here, as the ids are generated on the server side) and
b) if the applicationProfileId in the path and the applicationProfileIdin the requestBody do not match (that should be an error response)

**Expected behavior**

both topics can be avoided by using "PATCH" and in the requestBody NetworkQualityThresholds (or some UpdateApplicationProfile structure). That would be consistent with createProfile and with the description: "Update the network quality thresholds for an application ...". In this case you need to define that the NetworkQualityThresholds are replaced as a whole.

**Alternative solution**

**Additional context**

**Comment by maheshc01** [comment]
fixed with commit https://github.com/camaraproject/ConnectivityInsights/commit/a02c36e36d3b1267a185eb61f0cb1a631e983266
