### ISSUE TITLE
check: Application profile definition

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/ConnectivityInsights#88]
**Problem description**

L313 ApplicationProfile definition:
shouldn't the applicationProfileId be required?
would an (optional) name (freely chosen by the API user) make sense?
**Expected behavior**

- make applicationProfileId mandatory
- discuss whether  an (optional) name (freely chosen by the API user) make sense, and implement it if agreed.

**Alternative solution**

**Additional context**

**Comment by maheshc01** [comment]
application profile id as well as the object to define the thresholds have been marked as required.

**Comment by maheshc01** [comment]
fixed in a02c36e
