### ISSUE TITLE
check: alignment with common.yaml errors

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/ConnectivityInsights#89]
**Problem description**

From L358: error responses whould follow this in 
**Expected behavior**

Errors do not align with those in common.yaml

**Alternative solution**

consider to copy the used responses from https://github.com/camaraproject/Commonalities/blob/main/artifacts/CAMARA_common.yaml for consistency (but most responses do not apply for this API).  
**Additional context**

**Comment by maheshc01** [comment]
fixed with [542013c](https://github.com/camaraproject/ConnectivityInsights/pull/67/commits/542013ceda36ee11b963b5fb7ccac63b3c874a3f)
