### ISSUE TITLE
It looks that each event type has separate component defined:

### ISSUE THREAD

**Issue by maheshc01** [camaraproject/ConnectivityInsights#95]
It looks that each event type has separate component defined:
```suggestion
          org.camaraproject.connectivity-insights-subscriptions.v0.network-quality-met:
            "#/components/schemas/EventNetworkQualityMet"
           org.camaraproject.connectivity-insights-subscriptions.v0.network-quality-not-met:
            "#/components/schemas/EventNetworkQualityNotMet"
```
Following suggestions for lines 891-898

_Originally posted by @rartych in https://github.com/camaraproject/ConnectivityInsights/pull/67#discussion_r1725418729_

**Comment by maheshc01** [comment]
limiting to 2 events, EventNetworkQuality and EventSubscriptionEnds.
Both network-quality-met and network-quality-met is being handled in network-quality.

**Comment by maheshc01** [comment]
issue fixed in commit [630372b](https://github.com/camaraproject/ConnectivityInsights/pull/67/commits/630372b35ec23abd958e129a5c45e49e1876354a)

**Comment by rartych** [comment]
@maheshc01 I followed the approach used in:
https://github.com/camaraproject/DeviceLocation/blob/main/code/API_definitions/geofencing-subscriptions.yaml
https://github.com/camaraproject/DeviceStatus/blob/main/code/API_definitions/device-reachability-status-subscriptions.yaml

**Comment by maheshc01** [comment]
Hi @rartych ,

I reviewed the approach taken by geofencing and device reachability. both of them have specific components defined for each event type which is understandable. I would still do it differently for device reachability and i will put a issue there for enhancement.

In case of connectivity insights the only event is network quality insights(other than subscription ends) and in the same components a number of threshold could either be marked as met vs not met (defined as enum).  we cannot have 2 events as met vs not-met as in most cases all the define KPIs thresholds will not be mapped to same enum. In most cases will always have a combination of thresholds which are met and some of them which are not met.

Hope this makes sense.
Let me know if you need any further clarifications.

**Comment by maheshc01** [comment]
thank you for the feedback and confirmation that 1 event type is good.
I will marked this issue as closed.
