### ISSUE TITLE
Release Management instructions for the M4 PR

### ISSUE THREAD

**Issue by maheshc01** [camaraproject/ConnectivityInsights#97]
Expected action

Create the release PR for r1.1 with the target versions for Fall24 meta-release (M4)

Additional context

See checklist in https://lists.camaraproject.org/g/wg-release-management/topic/meta_release_fall24_please/108038111

**Comment by hdamker** [comment]
It has to be r1.2, not r1.1.

See https://github.com/camaraproject/ReleaseManagement/blob/main/documentation/API_Release_Guidelines.md#api-release-numbering
